### ISSUE TITLE
Integrate measure values input in chart with the mappings tab defaults (Control in upper-right)

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/nepExplorer#136]
e.g. it uses the mappings by default and allows user to change it interactively without going to mapping tab

we should make this smaller in UI

**Comment by jwoolfolk** [comment]
@pburnsdata -  With the latest update to include additional measure values to the lab column and the addition of the vitals column to the mapping tab of the integrated safetyGraphics - NepExplorer app vs the stand alone not having a mapping tab included, can you explain on this further or has this item already been addressed? 

Sorry its been awhile so I just wanted to confirm before I removed this issue as being done.

**Comment by Lovemore-Gakava** [comment]
merged change to dev.
